### ISSUE TITLE
Error on geting token

### ISSUE THREAD

**Issue by pan-danio** [tp86/legimi#2]
Hey, 
i just tried your app and i got error right after connecting to legimi api. My error log is:

```lua
stack traceback:
        [C]: in function 'string.unpack'
        src/legimi.lua:71: in local 'unpackin'
        src/legimi.lua:81: in upvalue 'parseresponseparts'
        src/legimi.lua:107: in local 'gettoken'
        src/legimi.lua:160: in main chunk
        [C]: in ?
```

It seems like the response after trying to get token is bad. The login and password are correct. What am i doing wrong?

**Comment by tp86** [comment]
I have encountered other issues recently, but in downloading book part. Obtaining token seems to be working fine for me.

Basically, this "app" is reverse-engineered based on communication between original Legimi app and their service. It's an attempt to download books on OS not supported by Legimi app (Linux).
Use at your own risk. :wink:

Back to the issues, perhaps something in protocol changed - I don't understand their protocol exactly or have any specification.

Currently, I don't have much time and interest in supporting issues, but you're free to investigate on your own.

**Comment by tp86** [comment]
I had some free time and finally figured this out. I have hardcoded my device id and it's part of the login message. That's why getting token (session id, actually) doesn't work for anyone but me.

For my issue, it's unrelated. I have also hardcoded ebook version and some ebooks don't have such version.

I'll be working on fixing those issues and script refactor and let you know when it's ready.

**Comment by pan-danio** [comment]
Thanks, for your answer. I'm excited to try this when its ready!

I had no time recently to work on this project on my own, and sadly I do not think it will change in the near future. Only help I can offer is to using it and giving feedback.

**Comment by tp86** [comment]
Yeah, `rework` branch is not usable at the moment. I'm trying to make whole client more robust but it will take some time.

What's wrong with script is that I've hard-coded `deviceId` that's associated with my Kindle and account. That's why authentication doesn't work for anyone but me (sorry). I have created that script for personal use, so I didn't pay much attention to the protocol, I have just wanted it to work. Since it seems that more people are interested in it, I'll try to make it usable for others. But until then, you probably should use official client.

You can try to modify the script to use you device id [here](https://github.com/tp86/legimi/blob/main/src/legimi.lua#L94), but I'm not yet sure how you can register your Kindle/get its id without using official Windows client.

**Comment by tp86** [comment]
Hi, `rework` branch has been merged into `main`. You can try using script now and let me know how it works for you.

I have completely reworked script, added some more user-friendly error-handling and documentation.
